CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname TEXT NOT NULL CHECK (firstname <> ''),
    lastname TEXT NOT NULL CHECK (lastname <> ''),
    role INTEGER NOT NULL,
    username TEXT NOT NULL CHECK (username <> ''),
    password TEXT NOT NULL CHECK (password <> ''),
    active BOOLEAN
);

CREATE TABLE IF NOT EXISTS role(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role TEXT NOT NULL CHECK (role <> '')
);

INSERT INTO USERS(firstname, lastname, role, username, password, active)
VALUES('Alejandra', 'Flores', 'Admin', 'aleja@flores.com', '123', true);

-- CREATE TABLE IF NOT EXISTS ROLE(
--     id INTEGER PRIMARY KEY
-- );